### ISSUE TITLE
missing include directory

### ISSUE THREAD

**Issue by timblechmann** [jgsogo/conan-apache-apr#4]
i figured out that `CONAN_INCLUDE_DIRS_APACHE-APR` is not properly populated, so client code is unable to access the apr headers.
i'm quite new to conan, so i'm not sure how to properly fix this myself (happy to get my hands dirty with some guidance, though)

**Comment by jgsogo** [comment]
Recipe already contributed to ConanCenter, I'm archiving this repo

https://github.com/conan-io/conan-center-index/pull/1460
https://conan.io/center/apr/1.7.0
